"""Add payment_method to Order model

Revision ID: 4021f5cda9b9
Revises: 87aebc3dad8a
Create Date: 2025-03-22 16:19:32.151497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4021f5cda9b9'
down_revision = '87aebc3dad8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.alter_column('delivery_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('delivery_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
