"""Add cancelled_by and cancelled_at columns to Order model

Revision ID: 87aebc3dad8a
Revises: 
Create Date: 2025-03-22 15:49:39.811180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87aebc3dad8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_by', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('age')
        batch_op.drop_column('sex')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancelled_by')

    # ### end Alembic commands ###
