"""Add brand support

Revision ID: 9d34b311c225
Revises: 
Create Date: 2025-11-19 21:16:32.755539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d34b311c225'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create brand table if it doesn't exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'brand' not in tables:
        op.create_table('brand',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('image_url', sa.String(length=200), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        )
    else:
        # Check if updated_at exists in brand table
        brand_columns = [col['name'] for col in inspector.get_columns('brand')]
        if 'updated_at' not in brand_columns:
            with op.batch_alter_table('brand', schema=None) as batch_op:
                batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Add brand_id to product table
    product_columns = [col['name'] for col in inspector.get_columns('product')]
    if 'brand_id' not in product_columns:
        with op.batch_alter_table('product', schema=None) as batch_op:
            batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_product_brand_id', 'brand', ['brand_id'], ['id'])
    
    # Drop optional columns if they exist
    if 'is_verified_only' in product_columns:
        with op.batch_alter_table('product', schema=None) as batch_op:
            batch_op.drop_column('is_verified_only')
    
    user_columns = [col['name'] for col in inspector.get_columns('user')]
    if 'is_verified' in user_columns:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified_only', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint('fk_product_brand_id', type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
