"""Add Category model with image support

Revision ID: b5f364b4029d
Revises: 9d34b311c225
Create Date: 2025-11-19 21:40:58.890516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f364b4029d'
down_revision = '9d34b311c225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create category table if it doesn't exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'category' not in tables:
        op.create_table('category',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('image_url', sa.String(length=200), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        )
    
    # Add category_id to product table if it doesn't exist
    product_columns = [col['name'] for col in inspector.get_columns('product')]
    if 'category_id' not in product_columns:
        with op.batch_alter_table('product', schema=None) as batch_op:
            batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_product_category_id', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove category_id from product
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    product_columns = [col['name'] for col in inspector.get_columns('product')]
    
    if 'category_id' in product_columns:
        with op.batch_alter_table('product', schema=None) as batch_op:
            batch_op.drop_constraint('fk_product_category_id', type_='foreignkey')
            batch_op.drop_column('category_id')
    
    # Drop category table
    op.drop_table('category')

    # ### end Alembic commands ###
